[package]
name = "unplug"
version = "0.1.0"
authors = ["Ben Cressey <bcressey@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc.workspace = true
seccompiler.workspace = true
