name: Rust
on:
  # triggers when a PR is posted
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
      - "**.plantuml"
      - "**.svg"
jobs:
  build:
    runs-on:
      group: bottlerocket
      labels: bottlerocket_ubuntu-latest_16-core
    steps:
      - uses: actions/checkout@v3
      - name: Install crane for testing
        uses: ./.github/actions/install-crane
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo install cargo-deny --locked
      - run: cargo install cargo-make --locked
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.18"
      - run: make build
